# Generated by Django 4.2.25 on 2025-10-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Recipient's email address", max_length=254
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        help_text="Site that issued the coupon", max_length=255
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique coupon code provided to the user",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of creation"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the coupon expires"),
                ),
                (
                    "redeemed",
                    models.BooleanField(
                        default=False, help_text="Whether the coupon has been used"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "website"], name="coupons_cou_email_f47192_idx"
                    )
                ],
            },
        ),
    ]
